title: Caroline Amado
description: Caroline Amado's Blog

url: http://carolineamado.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: carolineamado
   twitter: carolamado_
   facebook: carolineriot
   email: carolaraujoamado@gmail.com

google_analytics: "UA-68474615-1"
