# Site settings
title: Caroline Amado
email: carolaraujoamado@gmail.com
url: http://carolineamado.github.io/
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Telecommunication Engineer"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2c3e50 
  primary-rgb: "24,288,156"
  secondary: 2c3e50
  secondary-dark: 2c3e50

# Footer settings
footer:
  #copyright: Caroline Amado
  #location: Sao Paulo
  social: Around the Web
  #credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/carolamado_
  - title: facebook
    url: http://www.facebook.com/carolineriot
  - title: linkedin
    url: https://www.linkedin.com/in/carolineamado
  - title: github
    url: http://github.com/carolineamado

# Postal address (add as many lines as necessary)
address:
  - line: Sao Paulo
  

# Credits content
credits: 'Keep it Simple'

# Build settings
markdown: kramdown
permalink: pretty
